# Generated by Django 4.1.3 on 2022-11-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(default='none', max_length=50)),
                ('customer', models.CharField(default='none', max_length=100)),
                ('invoice_amt', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('receipt_amt', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('address', models.CharField(default='none', max_length=150)),
                ('city', models.CharField(default='none', max_length=50)),
                ('state', models.CharField(default='none', max_length=50)),
                ('phone', models.CharField(default='none', max_length=150)),
                ('email', models.CharField(default='none', max_length=250)),
            ],
            options={
                'verbose_name': 'AR List',
            },
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(default='none', max_length=50)),
                ('name', models.CharField(default='none', max_length=50)),
                ('type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer'), ('location', 'Location')], default='none', max_length=20)),
                ('address', models.CharField(default='none', max_length=150)),
                ('address_2', models.CharField(default='none', max_length=150)),
                ('city', models.CharField(default='none', max_length=20)),
                ('state', models.CharField(default='none', max_length=20)),
                ('zip', models.IntegerField(null=True)),
                ('country', models.CharField(default='none', max_length=20)),
                ('phone', models.CharField(default='none', max_length=15)),
                ('phone2', models.CharField(default='none', max_length=15)),
                ('email', models.CharField(default='none', max_length=50)),
            ],
            options={
                'verbose_name': 'Parties List',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(default='none', max_length=50)),
                ('tdate', models.CharField(default='none', max_length=50)),
                ('supplier', models.CharField(default='none', max_length=50)),
                ('supplier_print_name', models.CharField(default='none', max_length=50)),
                ('item', models.CharField(default='none', max_length=250)),
                ('quantity', models.DecimalField(decimal_places=4, default='0.00', max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, default='0.00', max_digits=10, null=True)),
                ('extended', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('fob_unit_price', models.DecimalField(decimal_places=4, default='0.00', max_digits=10, null=True)),
                ('cogs_unit_price', models.DecimalField(decimal_places=4, default='0.00', max_digits=10, null=True)),
                ('cogs_extended', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(default='none', max_length=50)),
                ('location_id', models.IntegerField(null=True)),
                ('tdate', models.CharField(default='none', max_length=50)),
                ('customer', models.CharField(default='none', max_length=150)),
                ('item', models.CharField(default='none', max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('extended', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('foreign_extended', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('cogs_extended', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('credit', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Sales List',
            },
        ),
    ]
